- build.sc
- cats/src/io/github/iltotore/iron/catsSupport/package.scala
- cats/test/src/io/github/iltotore/iron/test/catsSupport/RuntimeSpec.scala
- main/test/src/io/github/iltotore/iron/test/main/CompileTimeSpec.scala
- main/test/src/io/github/iltotore/iron/test/main/RuntimeSpec.scala
- main/test/src/io/github/iltotore/iron/test/main/package.scala
- testCore/src/io/github/iltotore/iron/test/package.scala
Add cats module for basic cats features support.
Closes #12
> Add cats module

- iterable/src/io/github/iltotore/iron/iterable/constraint.scala
- main/src/io/github/iltotore/iron/compileTime.scala
- main/src/io/github/iltotore/iron/constraint/Constraint.scala
- main/src/io/github/iltotore/iron/constraint/IllegalValueError.scala
- main/src/io/github/iltotore/iron/constraint/package.scala
- main/test/src/io/github/iltotore/iron/test/main/package.scala
- numeric/src/io/github/iltotore/iron/numeric/constraint.scala
- string/src/io/github/iltotore/iron/string/constraint.scala
- testCore/src/io/github/iltotore/iron/test/package.scala
Fetch error enhancement changes
> Fetch upstream

- build.sc
- io/src/io/github/iltotore/iron/ioSupport/constraint.scala
- io/test/src/io/github/iltotore/iron/test/ioSupport/RuntimeSpec.scala
- string/src/io/github/iltotore/iron/string/constraint.scala
- string/test/src/io/github/iltotore/iron/test/string/RuntimeSpec.scala
Add `Exists` constraint.
Closes #21
> Add IO Module

- main/src/io/github/iltotore/iron/constraint/package.scala
- main/test/src/io/github/iltotore/iron/test/main/RuntimeSpec.scala
Add a `RuntimeOnly[B]` modifier. This modifier make the inner constraint "Runtime Only".
> Add RuntimeOnly modifier

- main/src/io/github/iltotore/iron/constraint/package.scala
- main/src/io/github/iltotore/iron/package.scala
- main/test/src/io/github/iltotore/iron/test/main/CompileTimeSpec.scala
> Add refined capability

- main/src/io/github/iltotore/iron/constraint/Consequence.scala
- main/src/io/github/iltotore/iron/constraint/package.scala
- numeric/src/io/github/iltotore/iron/numeric/constraint.scala
> feat: Add mathematical relations

- .github/workflows/ci.yml
- .github/workflows/release.yml
- build.sc
Publishing artifact automatically to Central each time a new version is released
> Publish artifact automatically for each release

- .github/workflows/ci.yml
- build.sc
- docs/_docs/index.md
- examples/formCats/README.md
- examples/formCats/src/io/github/iltotore/iron/formCats/Account.scala
- examples/formCats/src/io/github/iltotore/iron/formCats/HttpServer.scala
- examples/formCats/src/io/github/iltotore/iron/formCats/Main.scala
- examples/formZio/README.md
- examples/formZio/src/io/github/iltotore/iron/formZio/Account.scala
- examples/formZio/src/io/github/iltotore/iron/formZio/HttpServer.scala
- examples/formZio/src/io/github/iltotore/iron/formZio/Main.scala
> docs: Add examples using ZIO and Cats

- main/src/io/github/iltotore/iron/conversion.scala
- main/src/io/github/iltotore/iron/package.scala
Closes #74
@gvolpe, can you confirm this PR solves your problem?
> fix: Ambiguous implicit for automatic refinement

- build.sc
- cats/src/io/github/iltotore/iron/cats.scala
- cats/test/src/io/github/iltotore/iron/CatsSuite.scala
fixes #75
Added a bunch of tests so next time should be more difficult to break it :)
> fix ambiguous cats instances

- main/src/io/github/iltotore/iron/constraint/string.scala
- main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
Hi there 👋 
Awesome project, love the v2 changes! I was experimenting with it at one of our apps and one of the refined types I tend to abuse (particularly when it comes to user input) is non-empty strings. So I thought you might be interested in having this here?
Let me know if there's anything that I need to do more for the PR (tests, etc)
> Add constraint for non-blank strings

- main/src/io/github/iltotore/iron/constraint/collection.scala
- main/src/io/github/iltotore/iron/constraint/string.scala
- main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
> fix: URL regex not matching valid URLs

- main/src/io/github/iltotore/iron/constraint/any.scala
- main/test/src/io/github/iltotore/iron/testing/AnySuite.scala
- main/test/src/io/github/iltotore/iron/testing/package.scala
- Add True/False constraints
- Add Xor operator
Related to #81
> feat: Add common boolean constraints

- main/src/io/github/iltotore/iron/compileTime.scala
- main/src/io/github/iltotore/iron/constraint/collection.scala
- main/src/io/github/iltotore/iron/conversion.scala
- main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala
> feat: Add common collection constraints

- main/src/io/github/iltotore/iron/constraint/collection.scala
- main/src/io/github/iltotore/iron/constraint/string.scala
- main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala
- main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
> feat: Add common string constraints

- README.md
- build.sc
- docs/_docs/modules/index.md
- docs/_docs/modules/zio.md
- docs/sidebar.yml
- zio/src/io/github/iltotore/iron/zio.scala
> feat: Add ZIO module

- .github/workflows/release.yml
Fix parsing error from `release.yml`
> fix: Bad quoting in `release.yml`

- README.md
- docs/_docs/modules/cats.md
- docs/_docs/modules/circe.md
- docs/_docs/modules/zio-json.md
- docs/_docs/modules/zio.md
- docs/_docs/overview.md
Made sure that all snippets compile.
This process could be automated later using Scaladoc's Scastie integration but this is not a priority yet.
> fix: Code snippets in README and website

- README.md
- docs/_docs/modules/cats.md
- docs/_docs/modules/circe.md
- docs/_docs/modules/index.md
- docs/_docs/modules/jsoniter.md
- docs/_docs/modules/zio-json.md
- docs/_docs/modules/zio.md
- docs/_docs/overview.md
- docs/_docs/reference/constraint.md
- docs/sidebar.yml
Polish documentation before v2.0.0.
- All examples compile using the latest version
- Added Jsoniter documentation
- Other minor changes
Closes #62
> docs: Polish documentation

- main/src/io/github/iltotore/iron/constraint/collection.scala
- main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala
Add a fixed size constraint on a collection length.
I think this is a worthy alias as we have a lot of internal use cases at day job.
> feat: Add FixedLength constraint

- main/src/io/github/iltotore/iron/package.scala
> Add an `unsafeAssume` method

- build.sc
> build: Version website

- main/src/io/github/iltotore/iron/RefinedTypeOps.scala
- main/test/src/io/github/iltotore/iron/testing/RefinedOpsSuite.scala
> feat: Merge `RefinedTypeOps#fromIronType` to `apply`

- main/src/io/github/iltotore/iron/RefinedTypeOps.scala
> refactor: Move base extension methods for RefinedTypeOpsImpl to class

- main/src/io/github/iltotore/iron/constraint/numeric.scala
- main/test/src/io/github/iltotore/iron/testing/NumericSuite.scala
> refactor: Remove Java's BigInt/BigDecimal constraints

- docs/_docs/modules/circe.md
Is the circe example missing a couple of imports?
> Add more circe imports

- docs/_docs/reference/newtypes.md
- main/src/io/github/iltotore/iron/constraint/any.scala
> feat: Add Pure alias for True

- docs/_docs/modules/cats.md
- docs/_docs/modules/circe.md
- docs/_docs/modules/jsoniter.md
- docs/_docs/modules/zio-json.md
- docs/_docs/modules/zio.md
> docs: Add examples' dependencies to docs

- main/src/io/github/iltotore/iron/constraint/numeric.scala
- main/test/src/io/github/iltotore/iron/testing/NumericSuite.scala
> feat: Support Multiple/Divide constraints for BigInt/BigDecimal

- main/src/io/github/iltotore/iron/RefinedTypeOps.scala
- main/src/io/github/iltotore/iron/package.scala
> feat: Add TypeTest instances and unapply for RefinedTypeOps

- build.sc
> docs: Link Iron sources to documentation

- build.sc
> docs: Link external libs' documentation

- build.sc
- cats/src/io/github/iltotore/iron/NegShift.scala
- cats/src/io/github/iltotore/iron/PosShift.scala
Not sure if there was a reason for not updating Scala to 3.3, but I thought to open this PR just in case it's needed
> Update Scala to 3.3.1

- main/src/io/github/iltotore/iron/constraint/any.scala
- main/test/src/io/github/iltotore/iron/testing/AnySuite.scala
> Remove Java BigDecimal and BigInteger instances

- README.md
- build.sc
- ciris/src/io.github.iltotore.iron/ciris.scala
- ciris/test/src/io/github/iltotore/iron/CirisSuite.scala
- ciris/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- docs/_docs/modules/ciris.md
- docs/sidebar.yml
> feat: Polish Ciris module

- README.md
- borer/test/src/io/github/iltotore/iron/BorerSuite.scala
- borer/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- docs/_docs/modules/borer.md
- docs/_docs/modules/index.md
- docs/sidebar.yml
- examples/borerSerialization/src/io/github/iltotore/iron/borerSerialization/Account.scala
- examples/borerSerialization/src/io/github/iltotore/iron/borerSerialization/main.scala
I forgot to include the new module in the module list in the README before...
> Add `iron-borer` to README

- .github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates
> add `dependabot.yml` for update github actions

- docs/_docs/modules/ciris.md
Replace link to circe with link to ciris on ciris.md
> Update ciris.md with correct link

- README.md
- build.sc
- docs/_docs/modules/pureconfig.md
- docs/sidebar.yml
- pureconfig/src/io/github/iltotore/iron/pureconfig.scala
- pureconfig/test/src/io/github/iltotore/iron/PureConfigExample.scala
- pureconfig/test/src/io/github/iltotore/iron/PureConfigSuite.scala
Add support for [PureConfig](https://pureconfig.github.io/docs/). Closes #263.
> feat: Add support for PureConfig

- docs/_docs/reference/constraint.md
- main/src/io/github/iltotore/iron/Constraint.scala
- main/src/io/github/iltotore/iron/RuntimeConstraint.scala
- main/src/io/github/iltotore/iron/constraint/any.scala
- main/src/io/github/iltotore/iron/constraint/char.scala
- main/src/io/github/iltotore/iron/constraint/collection.scala
- main/src/io/github/iltotore/iron/constraint/numeric.scala
- main/src/io/github/iltotore/iron/constraint/string.scala
- main/src/io/github/iltotore/iron/macros/ReflectUtil.scala
- main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala
> feat: Add compile-time support for non-primitive types

- main/src/io/github/iltotore/iron/macros/package.scala
Fix for [284](https://github.com/Iltotore/iron/issues/284).
> Fixed macro dealiasing

- build.sc
> build: Update ZIO JSON to 0.7.14

- docs/_docs/reference/config.md
- docs/_docs/reference/index.md
- docs/sidebar.yml
- main/src/io/github/iltotore/iron/internal/IronConfig.scala
- main/src/io/github/iltotore/iron/macros/ReflectUtil.scala
- main/src/io/github/iltotore/iron/macros/package.scala
> feat: Add better compile-time error messages

- main/src/io/github/iltotore/iron/compileTime.scala
- main/src/io/github/iltotore/iron/constraint/collection.scala
Continuation of #280.
Closes #279
> feat: Add remaining Array support

- borer/src/io/github/iltotore/iron/borer.scala
- borer/test/src/io/github/iltotore/iron/BorerSuite.scala
- borer/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- build.sc
- cats/src/io/github/iltotore/iron/cats.scala
- cats/src/io/github/iltotore/iron/instances.scala
- cats/test/src/io/github/iltotore/iron/CatsSuite.scala
- cats/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- circe/src/io/github/iltotore/iron/circe.scala
- ciris/src/io.github.iltotore.iron/ciris.scala
- ciris/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- decline/src/io/github/iltotore/iron/decline.scala
- decline/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- doobie/src/io/github/iltotore/iron/doobie.scala
- main/src/io/github/iltotore/iron/RefinedType.scala
- main/src/io/github/iltotore/iron/RefinedTypeOps.scala
- main/test/src/io/github/iltotore/iron/testing/RefinedOpsTypes.scala
- main/test/src/io/github/iltotore/iron/testing/RefinedTypeOpsSuite.scala
- pureconfig/src/io/github/iltotore/iron/pureconfig.scala
- pureconfig/test/src/io/github/iltotore/iron/PureConfigExample.scala
- skunk/test/src/io/github/iltotore/iron/SkunkExample.scala
- skunk/test/src/io/github/iltotore/iron/SkunkSuite.scala
- upickle/src/io/github/iltotore/iron/upickle.scala
- zio/src/io/github/iltotore/iron/zio.scala
- zio/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
- zio/test/src/io/github/iltotore/iron/ZIOSuite.scala
- zioJson/src/io/github/iltotore/iron/zioJson.scala
> Better new types definition

- main/src/io/github/iltotore/iron/constraint/string.scala
Current implementation of `check` macro for `Match` constraint allocate and compile the regex pattern every time.
This is not a problem when using compile time constraints, but runtime checks are slow and allocates a lot of memory because of this.
Solution is to precompile the regexp in a dedicated RuntimeConstraint instance.
> Prevent allocation of one regex per check

- main/src/io/github/iltotore/iron/RefinedType.scala
> feat: Add ops accessor to RefinedType.Mirror

- build.sc
- skunk/src/io.github.iltotore.iron/skunk.scala
- skunk/test/src/io/github/iltotore/iron/SkunkSuite.scala
> feat: Upgrade Skunk to 1.0.0-M10

- build.sc
- examples/formZio/src/io/github/iltotore/iron/formZio/HttpServer.scala
- examples/formZio/src/io/github/iltotore/iron/formZio/Main.scala
ZIO 2.1.6, ZIO-json 0.7.38 and zio-http 3.1.0
> :arrow_up: Bump ZIO deps

- examples/formJsoniter/src/io/github/iltotore/iron/formJsoniter/Account.scala
- jsoniter/src/io/github/iltotore/iron/jsoniter.scala
- jsoniter/test/src/io/github/iltotore/iron/JsoniterSuite.scala
> Add inline CodecMakerConfig parameter to jsoniter integration.

- borer/src/io/github/iltotore/iron/borer.scala
- circe/src/io/github/iltotore/iron/circe.scala
- ciris/src/io.github.iltotore.iron/ciris.scala
- decline/src/io/github/iltotore/iron/decline.scala
- doobie/src/io/github/iltotore/iron/doobie.scala
- pureconfig/src/io/github/iltotore/iron/pureconfig.scala
- upickle/src/io/github/iltotore/iron/upickle.scala
Fixes #317 
Implementing workaround suggested in
- https://github.com/Iltotore/iron/issues/317#issuecomment-2925158946
> De-inline given instances in external modules
