Iltotore/iron

.gitignore, main/src/io/github/iltotore/iron/compileTime.scala, main/src/io/github/iltotore/iron/constraint/IllegalValueError.scala, main/src/io/github/iltotore/iron/constraint/package.scala, main/src/io/github/iltotore/iron/package.scala
Fixes #2
Refined parameters now returns an instance of `Refined[A]` (alias for `Either[IllegalValueError[A], A]`).
=> Use monads for refinement

.github/workflows/main.yml, main/src/io/github/iltotore/iron/constraint/package.scala, main/test/src/io/github/iltotore/iron/test/CompileTimeSpec.scala, main/test/src/io/github/iltotore/iron/test/RuntimeSpec.scala, main/test/src/io/github/iltotore/iron/test/package.scala
This pull request provides the following constraints:
- `Not[B]`: Reverse the constraint represented by `B`
- `Or[B, C]` alias `||`: Pass if the input satisfies `B` or `C` one.
- `And[B, C]` alias `&&`: Pass if the input satisfies both `B` and `C`
These new boolean-like constraints allow constraint composition for complex cases.
=> Add boolean-like operations

build.sc, numeric/README.md, string/README.md, string/src/io/github/iltotore/iron/string/constraint.scala, string/test/src/io/github/iltotore/iron/test/string/RuntimeSpec.scala
This pull request adds `iron-string`, a String-related module for Iron.
It provides type constraints for String:
- LowerCase
- UpperCase
- Match[V] where V is a regex
=> String module for Iron

build.sc, iterable/README.md, iterable/src/io/github/iltotore/iron/iterable/constraint.scala, iterable/test/src/io/github/iltotore/iron/test/iterable/RuntimeSpec.scala
This Pull Request adds an iterable-related module for Iron. It includes custom constraints for Iterables:
- MinSize[V]
- MaxSize[V]
- Size[V]
- Empty = Size[0]
- Contains[V]
Related: #9
=> Add iterable module

iterable/src/io/github/iltotore/iron/iterable/constraint.scala, main/src/io/github/iltotore/iron/compileTime.scala, main/src/io/github/iltotore/iron/constraint/Constraint.scala, main/src/io/github/iltotore/iron/constraint/IllegalValueError.scala, main/src/io/github/iltotore/iron/constraint/package.scala, main/test/src/io/github/iltotore/iron/test/main/package.scala, numeric/src/io/github/iltotore/iron/numeric/constraint.scala, string/src/io/github/iltotore/iron/string/constraint.scala, testCore/src/io/github/iltotore/iron/test/package.scala
Closes #15 
`Constraint#assert` still returns a Boolean and a `Constraint#getMessage` method was added instead to prevent regression of the compile-time evaluation system.
=> Improve error handling system

main/src/io/github/iltotore/iron/constraint/package.scala
These constraints are now declared as RuntimeOnly to avoid confusion since their not fully inline.
Closes #25
=> Fix compile/runtime only incoherence for Not/Or/And constraints

numeric/src/io/github/iltotore/iron/numeric/constraint.scala
In its current state, `Even[A]` isn't that useful and `A % 2` is often preferred. The discussion #27 showed that `Even[A]` is more useful and has more use cases. Despite its redudancy (`A ==> Even[A]`), `Even[A]` as a `Constraint` is useful for type aliases and provides a useful abstraction on numbers:
```scala
type +>[A, B] = A ==> Greater[A] && Even[B] //No need to match on A to get the right literal type for `Divisible[V]`
```
Closes #31
=> Even[A] is now a constraint

main/src/io/github/iltotore/iron/compileTime.scala, main/src/io/github/iltotore/iron/constraint/Consequence.scala, main/src/io/github/iltotore/iron/constraint/LowPriorityConsequence.scala, main/src/io/github/iltotore/iron/constraint/package.scala, main/src/io/github/iltotore/iron/package.scala, main/test/src/io/github/iltotore/iron/test/main/CompileTimeSpec.scala, testCore/src/io/github/iltotore/iron/test/package.scala
Add a new "consequence" system allowing the system to assume some properties based on the given Constrained. For example, `A / (B1 & B2)` requires no evaluation to become `A / B1` or `A / B2`.
Closes #38
=> Add consequences

main/src/io/github/iltotore/iron/constraint/package.scala, string/src/io/github/iltotore/iron/string/compileTime.scala, string/src/io/github/iltotore/iron/string/constraint.scala, string/test/src/io/github/iltotore/iron/test/string/CompileTimeSpec.scala, string/test/src/io/github/iltotore/iron/test/string/RuntimeSpec.scala
This PR introduces compile time checking for `LowerCase`, `UpperCase` and `Match`.
Because `inline given [V] SomeClassThatRequiresV[V]` is not really inlined in compile time - from my understanding it must be generated for given V so I guess that breaks inlining - to get compile time checking for Match, `inline given MatchConstraint[CustomMatch] with {}` must be declared.
=> Compile time checking for string module

build.sc, cats/src/io/github/iltotore/iron/cats.scala, examples/catsValidation/src/io/github/iltotore/iron/catsValidation/Main.scala, examples/catsValidation/src/io/github/iltotore/iron/catsValidation/README.md, examples/formCats/src/io/github/iltotore/iron/formCats/HttpServer.scala, examples/formCats/src/io/github/iltotore/iron/formCats/Main.scala
Most users have moved away from explicitly using `Validated` and its variants. Instead, most of us use `Either` and its variants `EitherNec` and `EitherNel` together with the `Parallel` methods such as `parMapN`, which uses `Validated` instances before transforming it back to `Either`. 
- renames `refineNec` -> `refineValidatedNec`
- renames `refineNel` -> `refineValidatedNel`
- adds `refineNec` returning `EitherNec`
- adds `refineNel` returning `EitherNel`
- adds `catsValidation` example to showcase `refineNel` and `parMapN`
I'd like to get your feedback before I update the documentation. I propose to promote the usage of `Either` in the docs.
=> cats: add refineEither* methods

build.sc, examples/formJsoniter/src/io/github/iltotore/iron/formJsoniter/Account.scala, examples/formJsoniter/src/io/github/iltotore/iron/formJsoniter/main.scala, jsoniter/src/io/github/iltotore/iron/jsoniter.scala, jsoniter/test/src/io/github/iltotore/iron/JsoniterSuite.scala
Implements the feature requested in #82.
In this implementation, we're generating the codec for the underlying type within the `given` / method itself. This is only possible since the method is inlined, so type `A` is actually known when we create the codec. The implementation is largely based off the approach recommended by the library: https://github.com/plokhotnyuk/jsoniter-scala/blob/7da4af1c45e11f3877708ab6d394dad9f92a3766/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodeMakerNewTypeSpec.scala#L16-L45
One potential improvement to this is to add another method that accepts `CodecMakerConfig` but I wanted to keep it simple for the time being.
I've also included a basic example on how the jsoniter module can be used to create Jsoniter …
=> Add module for `jsoniter-scala` json codecs

main/src/io/github/iltotore/iron/constraint/collection.scala, main/src/io/github/iltotore/iron/constraint/string.scala, main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
This PR contains some microoptimizations for the following constraints:
* `MinLength` / `MaxLength`: `.length` / `.size` during runtime is calculated by iterating over the entire collection. This can be avoided by using `.sizeCompare` which breaks the iteration once the RHS value has been reached
* `UpperCase` / `LowerCase`: Instead of converting the string and then comparing it, iterate over the characters and break if any of them is not upper/lowercase. This avoids the creation of the additional string object during runtime.
There is another issue with `.toLowerCase` and `.toUpperCase` which I believe that this PR also address by this change. On the JVM, these methods are locale-specific (see below). I'm not 100% sure whether the changes I introduced fix this, I'll need to look into it.
=> Micro-optimizations for Length and Upper/Lowercase constraints

main/src/io/github/iltotore/iron/constraint/all.scala, main/src/io/github/iltotore/iron/constraint/char.scala, main/src/io/github/iltotore/iron/constraint/collection.scala, main/src/io/github/iltotore/iron/constraint/string.scala, main/src/io/github/iltotore/iron/conversion.scala, main/test/src/io/github/iltotore/iron/testing/CharSuite.scala, main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala, main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
Related to #81.
This PR adds the following constraints:
- Char:
- `Digit` using `Char#isDigit`
- `Letter` using `Char#isLetter`
- `Whitespace` using `Char#isWhitespace`
- `Special` alias for `Not[Digit] & Not[Letter]`
- Collections:
- `ForAll[C]`: tests if all elements satisfy the given constraint. Works at compile time for `String`.
- String:
- `Blank` alias for `ForAll[Whitespace]`
- `LettersLowerCase` alias for `ForAll[Not[Letter] | LowerCase]`. Replaces `LowerCase` for `String`.
- `LettersUpperCase` alias for `ForAll[Not[Letter] | UpperCase]`. Replaces `UpperCase` for `String`.
- `Alphanumeric` is now an alias for `ForAll[Digit | Letter]` instead of `Match["[0-9a-zA-Z]+"]`
Example of `ForAll`:
```scala
val digitCode: String :| ForAll[Digit] = "123" //OK
val invalid: String :| …
```
=> feat: Add common char constraints

main/src/io/github/iltotore/iron/compileTime.scala, main/src/io/github/iltotore/iron/constraint/numeric.scala, main/src/io/github/iltotore/iron/package.scala, main/test/src/io/github/iltotore/iron/testing/NumericSuite.scala
- Make numeric constraints usable with different types (e.g `Double :| Greater[0]`)
- Add Positive, Negative, Even, Odd, NaN and Infinity constraints
- Remove unused `IntNumber` and move `Number` to `io.github.iltotore.iron.compileTime.NumConstant`
Related to: #81
=> feat: Add common numeric constraints

README.md, build.sc, docs/_docs/modules/index.md, docs/_docs/modules/scalacheck.md, docs/sidebar.yml, scalacheck/src/io/github/iltotore/iron/scalacheck/Adjacent.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/Max.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/Min.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/any.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/char.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/collection.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/macros.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/numeric.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/string.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/AnySuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/CollectionSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/NumericSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/StringSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/package.scala
Add `org.scalacheck.Arbitrary` instances for refined types.
Closes #66
=> feat: Add Scalacheck module

main/src/io/github/iltotore/iron/constraint/any.scala
=> fix: Too restrictive type `V` for `StrictEqual`

main/src/io/github/iltotore/iron/internal/Validation.scala, main/src/io/github/iltotore/iron/macros/intersection.scala, main/src/io/github/iltotore/iron/macros/package.scala, main/src/io/github/iltotore/iron/macros/union.scala, main/src/io/github/iltotore/iron/util/Validation.scala
New messages are inspired from [kitlangton/neotype](https://github.com/kitlangton/neotype).
Union/Intersection:
```scala
final class Foo
final class Bar
val x: Int :| (Even | Foo | Bar) = 5
```
```
-- Compile-time Error ------------------------------------------------------
Missing given instances of Constraint[scala.Int, ...] in union for types:
- Main.Foo
- Main.Bar
----------------------------------------------------------------------------
```
Constraint not passing at compile-time:
```scala
val x: Int :| Positive = -1
```
```
-- Compile-time Error ------------------------------------------------------
A constraint did not pass for type scala.Int.
Value: -1
Message: Should be strictly positive
----------------------------------------------------------------------------
```
Closes #111 …
=> feat: Beautify compile-time errors

cats/src/io/github/iltotore/iron/cats.scala, docs/_docs/reference/refinement.md, main/src/io/github/iltotore/iron/compileTime.scala, main/src/io/github/iltotore/iron/constraint/any.scala, main/src/io/github/iltotore/iron/constraint/numeric.scala, main/src/io/github/iltotore/iron/constraint/string.scala, main/src/io/github/iltotore/iron/conversion.scala, main/src/io/github/iltotore/iron/internal/Validation.scala, main/src/io/github/iltotore/iron/macros/package.scala, main/src/io/github/iltotore/iron/macros/union.scala, main/src/io/github/iltotore/iron/package.scala, zio/src/io/github/iltotore/iron/zio.scala
Add `refineFurther` (and monadic variants) to enable fine-grained refinement of the same value. Here is the motivating example in docs:
```scala
type Username = DescribedAs[Alphanumeric, "Username should be alphanumeric"]
type Password = DescribedAs[
Alphanumeric & MinLength[5] & Exists[Letter] & Exists[Digit],
"Password should have at least 5 characters, be alphanumeric and contain at least one letter and one digit"
]
case class User(name: String :| Username, password: String :| Password)
def createUser(name: String, password: String): Either[String, User] =
for
validName     <- name.refineEither[Username]
alphanumeric  <- password.refineEither[Alphanumeric]
minLength     <- alphanumeric.refineFurtherEither[MinLength[5]]
hasLetter     <- minLength.refineFurtherEither[Exists[Letter]] …
```
=> feat: Add refineFurther methods to chain refinements

build.sc, cats/src/io/github/iltotore/iron/cats.scala, cats/test/src/io/github/iltotore/iron/CatsSuite.scala, docs/_docs/getting-started.md, docs/_docs/modules/cats.md, docs/_docs/modules/zio.md, main/src/io/github/iltotore/iron/RefinedTypeOps.scala, main/test/src/io/github/iltotore/iron/testing/RefinedOpsSuite.scala, zio/src/io/github/iltotore/iron/zio.scala, zio/test/src/io/github/iltotore/iron/ZIOSuite.scala
Not sure how to proceed with `opaque` types.
Very basic lib extensions are not working for opaque types:
```
opaque type Temperature = Double :| Positive
val t: Temperature = 2
```
Hence, I not even sure if I should try to dive deeper
=> [WIP] IRON-117 companion for refined new types

main/src/io/github/iltotore/iron/conversion.scala, main/src/io/github/iltotore/iron/macros/package.scala
Should fix #122 
This now compiles:
```scala
opaque type FirstName = String :| True
object FirstName extends RefinedTypeOps[FirstName]
```
```scala
val rawName = "Raf"
val name = FirstName(rawName)
```
@antonkw, does it solve your problem?
=> fix: Remove redundant restriction at compile-time

main/src/io/github/iltotore/iron/constraint/any.scala, main/test/src/io/github/iltotore/iron/testing/AnySuite.scala
=> Added type alias to constrain values to a set

main/src/io/github/iltotore/iron/compileTime.scala, main/src/io/github/iltotore/iron/constraint/any.scala, main/src/io/github/iltotore/iron/constraint/numeric.scala, main/test/src/io/github/iltotore/iron/testing/AnySuite.scala, main/test/src/io/github/iltotore/iron/testing/NumericSuite.scala
Fix for #132.
I could not get compile time checking to work using macros and so removed them. Any suggestions?
**Macro**
```scala
def testBigInt(e1: Expr[BigInt], e2: Expr[Long])(using Quotes): Expr[Boolean] = 
'{ $e1 > BigInt($e2) }
def testBigInt0(e1: Expr[BigInt])(using Quotes): Expr[Boolean] = 
'{ $e1 > bigInt0 }
```
**Error**
```
[error]  9 |  val x: BigInt :| Greater[0] = BigInt(1)
[error]    |                                ^^^^^^^^^
[error]    |-- Constraint Error --------------------------------------------------------
[error]    |Cannot refine value at compile-time because the predicate cannot be evaluated.
[error]    |This is likely because the condition or the input value isn't fully inlined.
[error]    |
[error]    |To test a constraint at runtime, use the `refined` extension …
```
=> Added support for BigDecimal and BigInt

cats/src/io/github/iltotore/iron/cats.scala, cats/test/src/io/github/iltotore/iron/CatsSuite.scala, cats/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala, circe/src/io/github/iltotore/iron/circe.scala, main/src/io/github/iltotore/iron/RefinedTypeOps.scala, main/test/src/io/github/iltotore/iron/testing/RefinedOpsSuite.scala, main/test/src/io/github/iltotore/iron/testing/RefinedOpsTypes.scala, main/test/src/io/github/iltotore/iron/testing/package.scala, zio/src/io/github/iltotore/iron/zio.scala, zio/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala, zio/test/src/io/github/iltotore/iron/ZIOSuite.scala, zioJson/src/io/github/iltotore/iron/zioJson.scala
=> test: Add given instances for `RefinedTypeOps`

main/src/io/github/iltotore/iron/constraint/collection.scala
Scala's Function1 doesn't have a specialization on `Char`, which means that each char in a string that is evaluated is boxed. This causes unnecessary object allocations when refining values that are not statically known.
This PR fixes this issue by reimplementing these methods they are in the std library, but using an `EvalChar` argument instead which prevents boxing
=> Use non-boxing `forall` and `exists` methods on strings

cats/src/io/github/iltotore/iron/cats.scala
=> fix: Ambiguous implicit when both `Eq[A]` and `Hash[A]` are available

build.sc, docs/_docs/getting-started.md, docs/_docs/modules/cats.md, docs/_docs/modules/circe.md, docs/_docs/modules/jsoniter.md, docs/_docs/modules/scalacheck.md, docs/_docs/modules/zio-json.md, docs/_docs/modules/zio.md, docs/_docs/overview.md, docs/_docs/reference/constraint.md, docs/_docs/reference/implication.md, docs/_docs/reference/iron-type.md, docs/_docs/reference/newtypes.md, docs/_docs/reference/refinement.md
Closes #151 
Snippets are not compilable yet due to several Scaladoc bugs.
=> docs: Prepare documentation for snippet checking

cats/src/io/github/iltotore/iron/cats.scala, main/src/io/github/iltotore/iron/RefinedTypeOps.scala, main/src/io/github/iltotore/iron/RuntimeConstraint.scala, zio/src/io/github/iltotore/iron/zio.scala
=> Add RuntimeConstraint

build.sc, ciris/src/io.github.iltotore.iron/ciris.scala, ciris/test/src/io/github/iltotore/iron/CirisSuite.scala
I was using a generic implicit to use iron with [ciris](https://cir.is/). It works fine for me.  I have added a test, which is mostly a smoke test to see that it works. It does however perform a proper summon of a `ciris.ConfigDecoder`
let me know what else to do/change.
=> feat: Support for ciris

cats/src/io/github/iltotore/iron/cats.scala, cats/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala, docs/_docs/reference/newtypes.md, docs/_docs/reference/refinement.md, main/src/io/github/iltotore/iron/RefinedTypeOps.scala, main/test/src/io/github/iltotore/iron/testing/RefinedOpsTypes.scala, main/test/src/io/github/iltotore/iron/testing/RefinedTypeOpsSuite.scala, zio/src/io/github/iltotore/iron/zio.scala, zio/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala
=> feat: Update RefinedTypeOps to support future Scala versions

main/src/io/github/iltotore/iron/RefinedTypeOps.scala
Closes #178 
@ajaychandran can you check if this PR solves your problem?
=> fix: Ambiguous given instance inside `RefinedTypeOps`

build.sc, upickle/src/io/github/iltotore/iron/upickle.scala, upickle/test/src/io/github/iltotore/iron/uPickleSuite.scala
I am not sure if you find this a useful addition. There's a circe module, so perhaps a upickle module fits?
=> upickle support

build.sc, doobie/src/io/github/iltotore/iron/doobie.scala
Add integration with the doobie data access library.
=> feature: Add doobie support

README.md, build.sc, docs/_docs/modules/skunk.md, docs/sidebar.yml, skunk/src/io.github.iltotore.iron/skunk.scala, skunk/test/src/io/github/iltotore/iron/SkunkExample.scala, skunk/test/src/io/github/iltotore/iron/SkunkSuite.scala
Adds support for [Skunk](https://typelevel.org/skunk).
=> Add support for skunk

docs/_docs/reference/constraint.md
Fix link to `StrictEqual` constraint, which is moved from `numeric` group to `any` in #70 
No any
=> Fix link to StrictEqual

.gitignore, README.md, build.sc, decline/src/io/github/iltotore/iron/decline.scala, decline/test/src/io/github/iltotore/iron/DeclineSuite.scala, decline/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala, docs/_docs/modules/decline.md, docs/sidebar.yml
Add support for [Decline](https://ben.kirw.in/decline/)
=> Add support for Decline

scalacheck/src/io/github/iltotore/iron/scalacheck/all.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/any.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/CollectionSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/ImplicitsOrderingSuite.scala
I tried to use scalacheck module with importing `io.github.iltotore.iron.scalacheck.all.given` - but I received the following error:
```
[E] [E1] scalacheck/test/src/io/github/iltotore/iron/scalacheck/ImplicitsOrderingSuite.scala:10:85
[E]      Ambiguous given instances: both given instance fallback in object all and given instance equivalence in object all match type org.scalacheck.Arbitrary[
[E]        io.github.iltotore.iron.IronType[String,
[E]          io.github.iltotore.iron.constraint.all.Empty]
[E]      ] of parameter arb of method testGen in package io.github.iltotore.iron.scalacheck
[E]      L10:     test("should resolve implicits using all.given import") - testGen[String, Empty]
[E]                                                                                               ^ …
```
=> Fix implicits priority

README.md, docs/_docs/modules/cats.md, docs/_docs/overview.md, docs/_docs/reference/refinement.md, main/src/io/github/iltotore/iron/conversion.scala, main/src/io/github/iltotore/iron/package.scala
=> Add deprecation to .refine, introduce .refineUnsafe instead

scalacheck/src/io/github/iltotore/iron/scalacheck/collection.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/string.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/CollectionSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/StringSuite.scala
I've observed, that generation of `String :| Not[Empty]` tends to fail to generate value from time to time (even up to 1.5% from my tests) <- because the generator used underneath from time to time selects 0 size for collection. 
This has caused some flaky tests for us when we had many such values generated and combined - then the probability of failing increases to `1 - 0.985^n` where n is number of values combined.
Scalacheck has built in function `Gen.nonEmptyBuildableOf` which can be used here. Not Empty case may be the most useful `Length[X]` case so it makes sense IMHO to optimise here. Similar thing is done in refined.
=> Add arbitraries for not empty collection/string which do not ever fail to generate value

docs/_docs/reference/newtypes.md
=> fix: Remove obsolete paragraph about `RefinedTypeOpsImpl`.

borer/src/io/github/iltotore/iron/borer.scala, borer/test/src/io/github/iltotore/iron/BorerSuite.scala, borer/test/src/io/github/iltotore/iron/RefinedOpsTypes.scala, build.sc, examples/borerSerialization/README.md, examples/borerSerialization/src/io/github/iltotore/iron/formBorer/Account.scala, examples/borerSerialization/src/io/github/iltotore/iron/formBorer/main.scala
This adds a new module (`iron-borer`) providing automatic refined type codec construction for the `CBOR` and `JSON` serialization library [borer](https://sirthias.github.io/borer/).
It also adds a new example module showcasing the integration.
This is my first contribution to iron, so please let me know if anything is off!
And thank you for iron!
It's an awesome addition to the Scala 3 ecosystem.
=> Add `iron-borer` integration module

scalacheck/src/io/github/iltotore/iron/scalacheck/collection.scala, scalacheck/src/io/github/iltotore/iron/scalacheck/string.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/CharSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/CollectionSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/NumericSuite.scala, scalacheck/test/src/io/github/iltotore/iron/scalacheck/package.scala
Hello @Iltotore 
This is a tiny PR that improves the generators. 
All generators are guaranteed to generate values with a 100% success
rate. The testGen function checks that. In case of exhausted case, an
exception is thrown.
Some generators had to be written specifically for that purpose.
Most of string generators reuse the collection generators.
Thanks for your project.
=> Improve performance of arbitraries 

cats/src/io/github/iltotore/iron/cats.scala, cats/test/src/io/github/iltotore/iron/CatsSuite.scala, docs/_docs/reference/refinement.md, main/src/io/github/iltotore/iron/MapLogic.scala, main/src/io/github/iltotore/iron/RefinedTypeOps.scala, main/src/io/github/iltotore/iron/conversion.scala, main/src/io/github/iltotore/iron/package.scala, main/test/src/io/github/iltotore/iron/testing/RefinedTypeOpsSuite.scala, zio/src/io/github/iltotore/iron/zio.scala, zio/test/src/io/github/iltotore/iron/ZIOSuite.scala
Add first order types support like ZIO Prelude's `wrapAll` and variants (option/either/unsafe/...) as well as equivalent methods for `RefinedTypeOps` and `...Further`.
Support for Cats' `Functor` and ZIO Prelude's `Covariant` and documentation are still in WIP.
Closes #202
=> feat: Support first order types

docs/_docs/reference/constraint.md
As I always struggled to remember pre-defined constraints, I added them to the mini-site.
=> 📝 docs: Add pre-defined constraints in documentation

main/src/io/github/iltotore/iron/macros/package.scala
=> fix: Change color of error message

main/src/io/github/iltotore/iron/constraint/char.scala, main/src/io/github/iltotore/iron/constraint/collection.scala, main/src/io/github/iltotore/iron/constraint/string.scala, main/src/io/github/iltotore/iron/internal/package.scala, main/src/io/github/iltotore/iron/macros/ReflectUtil.scala, main/src/io/github/iltotore/iron/macros/package.scala
=> feat: Better compile time diagnostics

main/src/io/github/iltotore/iron/macros/ReflectUtil.scala, main/src/io/github/iltotore/iron/macros/package.scala
Enhance error messages and support some other cases at compile time.
Partly closes #238. Other cases are not doable because Scala cancel any folding/inlining for them.
=> feat: Better diagnostics

main/src/io/github/iltotore/iron/RefinedTypeOps.scala
It seems like `fromIronType` was combined with `apply` in `RefinedTypeOps`, but there are a few lingering references in the Scaladoc to the removed API member. This PR removes those references.
Close #248 
Related: #130 #139 #140
=> Remove references in docs to old function (`fromIronType`)

docs/_docs/reference/newtypes.md
just a small fix to one of the examples
=> Fix incorrect object name in docs

main/src/io/github/iltotore/iron/RefinedTypeOps.scala, main/src/io/github/iltotore/iron/macros/package.scala
`RefinedTypeOps#apply` now accepts `A` with a given `Constraint[A, C]` instance. Since most of the `Constraint` instances are non-orphan (aka defined inside the companion object of `C` or `A` or `Constraint`), they do not need to be imported.
```scala
package types
import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.numeric.Positive
opaque type Temperature = Double :| Positive
object Temperature extends RefinedTypeOps[Double, Positive, Temperature]
```
```scala
//No `io.github.iltotore.iron...` import needed
import types.Temperature
object Main:
@main
def testMain =
println(Temperature(100))
```
To be completely blackbox (excluding `RefinedTypeOps.Mirror`), Scala needs to support `inline` trait/constructor parameters.
=> feat: Allow both raw and refined types in RefinedTypeOps#apply

docs/_docs/index.md, docs/_docs/talks-and-articles.md, docs/sidebar.yml
Add links to videos and articles to the website. Closes #255
=> docs: Add links to videos and articles to the website

build.sc, cats/src/io/github/iltotore/iron/Bounds.scala, cats/src/io/github/iltotore/iron/cats.scala, cats/src/io/github/iltotore/iron/instances.scala, cats/test/src/io/github/iltotore/iron/CatsSuite.scala, cats/test/src/io/github/iltotore/iron/ShiftSuite.scala
Closes #271 
Closes #270 
Closes #268
=> feat: Polish Cats semigroups/monoids for refined types

main/src/io/github/iltotore/iron/constraint/collection.scala, main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala
Part of #279 
I have added support of  Length and Contain constraints for Arrays and update the docs of these constraints.
I have troubles with ForAll and other constraints checks if collection elements satisfy a constraint due to Array requiring a ClassTag for elements and therefore a problem with converting elements to expressions.  
Are you okay with a patch covering just a part of the original issue?
=> feat: Length and Contain constraints support for Array added

build.sc, main/src/io/github/iltotore/iron/constraint/any.scala, main/test/src/io/github/iltotore/iron/testing/AnySuite.scala
After 3.6.4 `Implication` from one `DescribedAs` to another has become ambiguous
```
|Note that implicit conversions cannot be applied because they are ambiguous;    
|                                             
|both given instance given_==>_DescribedAs_C2 in object DescribedAs and
|given instance given_==>_C1_DescribedAs in object DescribedAs match type 
|
|io.github.iltotore.iron.Implication[
|  io.github.iltotore.iron.constraint.any.DescribedAs[
|    io.github.iltotore.iron.True, ("test" : String)],
|  io.github.iltotore.iron.constraint.any.DescribedAs[
|    io.github.iltotore.iron.constraint.any.Not[io.github.iltotore.iron.False],
|    ("test" : String)]
|]
```
fixes #311
=> fix: DescribedAs Implication ambiguity

main/src/io/github/iltotore/iron/RefinedType.scala
There was `val ops = ops` expression (probably a typo), that led to runtime NPE.
[scastie](https://scastie.scala-lang.org/EDfkDV4NRsKk8ewxFG4Bgg)
=> fix: NPE in Mirror[T].ops

docs/_docs/modules/skunk.md, main/src/io/github/iltotore/iron/constraint/string.scala
This PR basically was intended to update the `skunk` module documentation, as the previous one used the deprecated `RefinedTypeOps` newtype generator. 
However, since the PR was going to be so small, I also wanted to include a `ValidEmail` constraint under the `constraints.string` package, since there are already constraints for UUIDs and URLs. I tried my best to create the email regex, but I don't know if it meets Iron's standards. I'm happy to change it if it doesn't!
That's pretty much it, have a nice one! 💖
=> Update documentation on `skunk` module and add `ValidEmail` constraint
